### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by eric72777** [kjhoerr/dotfiles#329]
I think there may be a typo. In line 62 of .config/nixos/systems/ariadne.nix, it says:
`hardware.cpu.intel.updateMicrocode = true;`
But line 137 of flake.nix suggests ariadne is an AMD, not intel:
`inputs.nixos-hardware.nixosModules.framework-13-7040-amd`

If ariande is an AMD Framework 13, should ariande.nix instead be: ` hardware.cpu.amd.updateMicrocode = true;`?

**Comment by kjhoerr** [comment]
Good catch! That's a holdover from when I had the Intel Framework. I think this is handled by the nixos-hardware profile anyways, so I'll remove the line.

Thanks!
