### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by babeuh** [kjhoerr/dotfiles#57]
I don't know if a license is completely required to reuse your config because I'm not sure copyright even applies to config files.

However, is there a license for this repo? I can't seem to find one.

If there isn't, it would be great if you added one to clarify if people are allowed to reuse your config.

**Comment by kjhoerr** [comment]
I would think it's a gray area for Nix or Guix configs - they're still technically code, though most people will be using very similar "scripts" that do very similar things, but I am not a lawyer. Regardless copyleft or proprietary licenses don't make sense for this kind of repo.

I opted to add MIT to the project - feel free to adopt this repository to your needs as is permissed by the license.
